version: '3.8'
services:
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
